- CHANGELOG.md
- pyproject.toml
- src/cappa/argparse.py
- src/cappa/base.py
- src/cappa/command.py
- src/cappa/completion/base.py
- src/cappa/completion/types.py
- src/cappa/parser.py
- src/cappa/testing.py
- tests/completion/test_base.py
- tests/parser/test_custom_callable_action.py
- tests/test_base.py
- tests/test_output.py
- tests/utils.py
* The command's name should now always translate to the prog name
* Explicitly provided argv should now **not** include the prog name
Fixes https://github.com/DanCardin/cappa/issues/14
> fix: Reference argv and prog consistently.

- src/cappa/help.py
- tests/help/test_completion_choices.py
Point 4 of the main command in #15.
Previous code was normalizing the argument twice, therefore appending the choices to the help message twice.
> Fix help of the completion argument

- src/cappa/typing.py
Following my comment in https://github.com/DanCardin/cappa/pull/11#issuecomment-1768331651 and some tests.
Feel free to reword the commit by squashing.
> De-indent PEP 727 documentation using `inspect.cleandoc`

- CHANGELOG.md
- pyproject.toml
- src/cappa/annotation.py
- src/cappa/command.py
- src/cappa/parser.py
- tests/arg/test_literal_mulitple_variant.py
- tests/completion/test_custom_completion.py
Fixes https://github.com/DanCardin/cappa/issues/18
> fix: Literal["one", "two"] syntax as choices.

- pyproject.toml
- src/cappa/arg.py
- src/cappa/parser.py
- tests/parser/test_concatenated_short_options.py
- tests/parser/test_multicharacter_short.py
Fixes https://github.com/DanCardin/cappa/issues/20
> feat: Better support for concatenated short args.

- docs/source/api.md
- docs/source/arg.md
- src/cappa/arg.py
- src/cappa/argparse.py
- src/cappa/completion/types.py
- src/cappa/invoke.py
- src/cappa/parser.py
- tests/parser/test_custom_callable_action.py
Attempt at addressing issue described in https://github.com/DanCardin/cappa/issues/7, where one cannot replicate --help/--version alike arguments. basically, you'd supply a callable as an action and `raise Exit`.
But i think the idea as implemented has some other nice side-effects. when using the native backend, it can use the invoke system to dependency-inject parser state very easily. the main question is whether or not it's a good idea to expose that parser state to downstream consumers.
It's certainly useful inside the parser itself to send arguments to the native handlers, so 🤷
> feat: Add ability to define custom action callable.

- CHANGELOG.md
- docs/source/invoke.md
- pyproject.toml
- src/cappa/invoke.py
- tests/invoke/test_command_dep.py
Fixes https://github.com/DanCardin/cappa/issues/40
> feat: Add cappa.Command as available invoke dependency.

- CHANGELOG.md
- docs/source/manual_construction.md
- pyproject.toml
- src/cappa/arg.py
- src/cappa/argparse.py
- src/cappa/command.py
- src/cappa/help.py
- src/cappa/invoke.py
- src/cappa/parser.py
- src/cappa/subcommand.py
- src/cappa/typing.py
- tests/arg/test_help.py
- tests/arg/test_name_disallowed.py
- tests/help/test_group.py
- tests/help/test_name.py
- tests/test_docstring.py
- tests/test_manually_built.py
Fix https://github.com/DanCardin/cappa/issues/46.
At current moment, `name` field is relatively inaccessible except for the "manual construction" usecase. It's otherwise able to be specified. Thus using such a valuable, generic name seemed unncessary. Thus `name` -> `field_name`.
~With `name` freed up, "name" seems like a decent name for the equivalent of `metavar` in argparse. I suppose `name` could be confused with short/long?~
I looked at Clap which uses [value_name](https://docs.rs/clap/latest/clap/struct.Arg.html#method.value_name), which i rather like, and which seems to me to pair well with `field_name`. certainly better than metavar
> feat: Split name and field_name on Arg object.

- pyproject.toml
- src/cappa/help.py
- src/cappa/parser.py
- tests/arg/test_value_name.py
- tests/help/test_name.py
Fixes https://github.com/DanCardin/cappa/issues/53
Fixes https://github.com/DanCardin/cappa/issues/54
> fix: Leave value_name formatting up to the user.

- CHANGELOG.md
- pyproject.toml
- src/cappa/argparse.py
- src/cappa/base.py
- src/cappa/command.py
- src/cappa/completion/base.py
- src/cappa/output.py
- src/cappa/parser.py
- src/cappa/subcommand.py
- src/cappa/testing.py
- tests/help/test_name.py
- tests/invoke/test_output.py
- tests/parser/test_custom_callable_action.py
- tests/parser/test_missing_num_args.py
- tests/test_output.py
- tests/utils.py
Fixes https://github.com/DanCardin/cappa/issues/43
Given
```python
def _debug(output: cappa.Output):
table = Table(style="blue")
table.add_row("one", "two")
output.error(table)
raise cappa.Exit(code=0)
@dataclass
class Example:
foo: str
debug_info: Annotated[
bool,
cappa.Arg(long=True, action=_debug, num_args=0),
Doc("Print debug information."),
] = False
output = cappa.Output(error_format="[red]Error[/red]:\n{message}!")
args: Example = cappa.parse(Example, output=output)
```
> feat: Add option to apply custom output/error formatting.

- docs/source/annotation.md
- docs/source/arg.md
- pyproject.toml
- src/cappa/annotation.py
- src/cappa/arg.py
- tests/arg/test_invalid_annotation_combination.py
- tests/test_e2e.py
Addresses suggestions extracted from https://github.com/DanCardin/cappa/issues/74, by disallowing combinations that would otherwise produce confusing results or runtime errors during mapping
> fix: Disallow certain combinations of apparently incompatible annotations.

- CHANGELOG.md
- pyproject.toml
- src/cappa/annotation.py
- src/cappa/arg.py
- tests/arg/test_parse.py
Without this, some field `foo: Annotated[int | None, Arg(parse=int)] = None`, which would **seem** like it should work (even if there's no need to use an explicit parse here), will fail because it unconditionally runs the parse.
Now, it will detect optional source types, and apply an optional aware wrapper around the given input `parse`.
If this behavior breaks something, i'd rather we handle that directly at time that it's identified. As-is, its not obvious why you'd annotate it as potentially `None`, if it shouldn't be allowed to be None.
> fix: Special case None type handling in combination with explicit `parse` functions.

- CHANGELOG.md
- docs/source/invoke.md
- pyproject.toml
- src/cappa/base.py
- src/cappa/invoke.py
- tests/invoke/test_async_generator_dependency.py
- tests/invoke/test_generator_dependency.py
The implementation for https://github.com/DanCardin/cappa/issues/76 lended itself to also enabling "yield" dependencies. I.e. dependencies which act as context managers through the use of `yield`.
Basically a feature I didn't realize I wanted until it came up that it'd be useful, and which was directly enabled by supporting asyncio in the invoke system two days earlier 😆
> feat: Implement yield dependencies.

- pyproject.toml
- src/cappa/arg.py
- src/cappa/typing.py
- tests/arg/test_bool.py
This causes `foo: bool` to automatically infer as `default=False`. As written currently, `bool` is automatically inferred as non-required, which necessitates there be a default.
I'm not sure whether I think this is ultimately preferable to removing the `required=False` inference, and instead having the behavior that the defaultedness of the field is the only indicator of whether it's required.
The reason that was introduced in the first place was because `--bool`, as a simple flag can **only** set something to `True`, and having it be required by default may be somewhat weird. However you certainly **can** specify `Annotated[bool, Arg(long=['--bool', '--no-bool'])]` and arrive at a place where a required bool **might** make sense.
It just generally feels to me that required options are …
>  fix: Default bool fields to False when omitted. 

- pyproject.toml
- src/cappa/annotation.py
- tests/arg/test_mapping_failure.py
Apparently Path constructor can yield TypeError.
It may be that we should just catch all exceptions here...erring on the side of caution for now.
> fix: Handle TypeError in mapping failure also.

- .github/workflows/test.yml
Seemingly better UX. With no other changes, I can see exact line misses in their UI, whereas coveralls claims to not have the source code
> chore: Switch to codecov.

- CHANGELOG.md
- pyproject.toml
- src/cappa/class_inspect.py
- src/cappa/invoke.py
- src/cappa/typing.py
- tests/command/test_function_command.py
Previously all args were translated to dataclass fields, i.e. CLI inputs, and `Dep`s would not be fullfilled
> feat: Support `Dep` on function based commands.

- CHANGELOG.md
- docs/source/annotation.md
- pyproject.toml
- src/cappa/arg.py
- src/cappa/parser.py
- tests/arg/test_invalid_annotation_combination.py
- tests/arg/test_tuple.py
- tests/parser/test_missing_num_args.py
- tests/parser/test_num_args.py
* Fixes bounded-tuple options like `tuple[str, str]` to infer as `num_args=2`
* Fixes bounded-tuple options to fail parsing if you give it a different number of values
* Fixes "double sequence" inference on explicit `num_args=N` values which would produce sequences. I.e. infer `action=ArgAction.set` in such cases to avoid e.x. `num_args=3, action=ArgAction.append`; resulting in nonsensical nested sequence `["[]"]`
Fixes https://github.com/DanCardin/cappa/issues/106
What does concern me slightly is that this allows something which was previously erroneous to specify:
```python
class Foo:
foo: Annotated[list[str], cappa.Arg(num_args=1, short=True)]
```
This was erroring because failed because the `num_args=1` implied a non-sequence type. However the inferred `action=ArgAction.append` …
> fix: Add better sequence inference.

- CHANGELOG.md
- pyproject.toml
PEP 727 was added in typing-extensions 4.8.0. 
Https://github.com/python/typing_extensions/blob/main/CHANGELOG.md
> chore: update typing-extensions to `>=4.8.0`

- CHANGELOG.md
- pyproject.toml
- src/cappa/arg.py
- src/cappa/base.py
- src/cappa/command.py
- src/cappa/parser.py
- tests/arg/test_default_long.py
- tests/arg/test_default_short.py
- tests/help/test_line_wrapping.py
i.e. 
```python
@cappa.command(default_long=True)
class Command:
foo: int = 4
bar: int = 5
```
results in `--foo` and `--bar` rather than `FOO BAR` positional arguments
> feat: Add `default_short=False` and `default_long=False` options to command for ease of definining option-heavy commands.

- .github/workflows/test.yml
- pyproject.toml
- src/cappa/arg.py
- src/cappa/argparse.py
- src/cappa/base.py
- src/cappa/command.py
- src/cappa/parser.py
- tests/arg/test_deprecated.py
- tests/subcommand/test_deprecated.py
Note argparse only supports this option since python 3.13. The way argparse is implemented, it seems like it'd be nontrivial to backport, so for now it's going to do nothing in versions that dont support it.
> feat: Add deprecated option to command/arg.

- CHANGELOG.md
- pyproject.toml
- src/cappa/class_inspect.py
This change handles a corner case where `pydantic` is installed in the environment but `pydantic-core` is missing. The current code assumes that if pydantic is importable, then pydantic is available, but the access of `pydantic.BaseModel` does [a lazy import](https://github.com/pydantic/pydantic/blob/7061f36bc721ef4f173ef8f2e098f25e1eaea705/pydantic/__init__.py#L383-L396) of `pydantic-core` which is not handled, crashing the application that is using `cappa`. 
To handle the issue, `BaseModel` is imported eagerly during the detection step, which will throw an error when `pydantic-core` is not available. 
I have observed this in the wild, where I am not using `pydantic` with cappa at all, nor it is one of my direct dependencies, but it is still being pulled transitively from other sources, …
> fix: handle missing pydantic-core corner case

- docs/source/class_compatibility.md
Fixe link to point to repo instead of current page anchor
> fix(docs): update link to msgpsec

- CHANGELOG.md
- docs/source/arg.md
- poetry.lock
- src/cappa/__init__.py
- src/cappa/arg.py
- src/cappa/argparse.py
- src/cappa/class_inspect.py
- src/cappa/command.py
- src/cappa/ext/docutils.py
- src/cappa/help.py
- src/cappa/invoke.py
- src/cappa/parser.py
- src/cappa/subcommand.py
- src/cappa/typing.py
- tests/arg/test_dataclass_metadata_invalid.py
- tests/arg/test_exclusive_group.py
- tests/subcommand/test_group.py
```python
arg: Annotated[
int,
cappa.Arg(short="-v", action=cappa.ArgAction.count),
cappa.Arg(long="--verbosity"),
] = 0
```
Is the proposed syntax for this so far. This might be nicer as `X | Y`, but that gets somewhat more magical implementation wise and it's not entirely clear that it's that much better, if at all.
---
What's unclear is whether this syntax is useful without also implying mutual exclusivity. I could imagine for an `int` target, `--verbosity 3 -v` might yield `arg == 4`. but ordering would become significant and most other types of inputs wouldn't make sense.
...granted this is essentially exactly how all of argparse's arguments work (unless there's validation i'm forgetting), relying on you to select metavars that dont conflict in stupid ways...
Ultimately, you'd still …
> feat: Implement exclusive groups.

- CHANGELOG.md
- pyproject.toml
- src/cappa/annotation.py
- src/cappa/command.py
- tests/arg/test_file_io.py
- tests/arg/test_literal.py
- tests/arg/test_literal_intermixed_union.py
- tests/arg/test_mapping_failure.py
- tests/arg/test_parse.py
As exemplified in the tests:
```
Invalid value for 'name': Possible variants
- Literal['one']: Invalid choice: 'thename' (choose from literal values 'one')
- int: invalid literal for int() with base 10: 'thename'
```
For some arbitrary bad value being routed through an option with some `Union[Literal['one'], int]` annotation.
Certainly one could get more specific and tailored error messages with custom parsers, as this is perhaps leaking python-isms out through the error messages, but this at least seems preferable to the original error: `Could not parse 'thename' given options: <int>, one`
Or worse, `set[Literal['one', 'two'] | None` was previously: `Could not parse '['three']' given options: <set>, <NoneType>`, but is now:
```
Invalid value for '-f': Possible variants
- …
```
> feat: Improve union error messages.

- CHANGELOG.md
- docs/source/help.md
- docs/source/index.md
- pyproject.toml
- src/cappa/__init__.py
- src/cappa/arg.py
- src/cappa/argparse.py
- src/cappa/base.py
- src/cappa/command.py
- src/cappa/ext/docutils.py
- src/cappa/help.py
- src/cappa/parser.py
- src/cappa/subcommand.py
- src/cappa/testing.py
- tests/arg/test_exclusive_group.py
- tests/help/test_help_formatter.py
- tests/utils.py
This enables one to include or exclude things like default values, or choices. Notably changes to include default values in help text by default.
Fixes https://github.com/DanCardin/cappa/issues/125
---
A kitchen-sink style example of most of the available options, used together.
```python
from cappa import parse, HelpFormatter, Arg
class Command:
foo: Annotated[str, Arg(help="Help text.", deprecated=True)] = "foo"
def deprecated(arg: Arg) -> str | None:
if arg.deprecated:
return "Deprecrated"
return None
parse(Command, help_formatter=HelpFormatter(arg_format=("{default}", "{help}", deprecated), default_format="(Default `{default}`)")
```
Resulting in something like `(Default `foo`) Help text. Deprecrated`.
> feat: Add `help_formatter` system wherein help text rendering can be customized.

- CHANGELOG.md
- pyproject.toml
- src/cappa/arg.py
- src/cappa/argparse.py
- src/cappa/invoke.py
- src/cappa/parser.py
- tests/arg/test_bool.py
Namely `ex: Annotated[bool, cappa.Arg(long=True, default=cappa.Env("EX"))] = False` was inferring `store_false`, when it ought to have been inferring `store_true`.
> fix: action inference when `default` is an `Env`.

- CHANGELOG.md
- docs/source/help.md
- pyproject.toml
- src/cappa/command.py
- src/cappa/docstring.py
- tests/help/test_docstring.py
- tests/utils.py
Fixes https://github.com/DanCardin/cappa/issues/129
> feat: Allow "attribute docstrings" as additional method of documenting args.

- README.md
See #135. Just a quick two-liner PR, though I collapsed some spacing so if you prefer a certain code style in your example docs it may need a once-over.
> Fix for non-functional subcommands example in docs

- CHANGELOG.md
- docs/source/arg.md
- pyproject.toml
- src/cappa/arg.py
- src/cappa/command.py
- src/cappa/env.py
- tests/arg/test_default.py
I can't really see why this would be undesirable behavior in the general case.
Technically **today**, you might supply `Annotated[int, Arg(default='')]` which wont fail to typecheck, and will now be the incorrect type. But there is active discussion about a PEP to enable the Annotated type to tie back to the Arg instance, which would address this. Plus, the Arg default is very much less desireable to use than the native python/dataclass one for exactly that reason.
When using native defaults, it should typecheck correctly, and this way **enables** one to use the correct type there, where they might have previously been **forced** to use the less desirable one.
Fixes issue discovered in https://github.com/DanCardin/cappa/discussions/137
> fix: Avoid applying annotated type parsing to default value.

- docs/source/arg.md
The default boolean actions are `ArgAction.store_true` and `ArgAction.store_false` and not `ArgAction.set_true` and `ArgAction.set_false`.
> Fix typo in ArgAction documentation

- CHANGELOG.md
- pyproject.toml
- src/cappa/arg.py
- src/cappa/argparse.py
- src/cappa/parser.py
- tests/arg/test_bool.py
Fixes https://github.com/DanCardin/cappa/issues/147
The only thing that feels kind of weird about the implementation here (which...it really shouldn't because it's basically exactly as arbitrary as it was before) is that given some `--foo/--no-foo`: `--foo` will unconditionally `store_true` and `--no-foo` will unconditionally `store_false`.
But given that level of information, i dont see how we could infer any other choice though, so it doesn't feel that arbitrary. And what's **nice** about this solution is that the user can now always manually expand the definition themselves to arrive at whatever behavior they want, without the parser inverting their stated selection.
> refactor: Pull handling of --no-* bool arguments out of the parser.

- Makefile
- pyproject.toml
- src/cappa/arg.py
- src/cappa/argparse.py
- src/cappa/class_inspect.py
- src/cappa/command.py
- src/cappa/ext/docutils.py
- src/cappa/help.py
- src/cappa/invoke.py
- src/cappa/parse.py
- src/cappa/parser.py
- src/cappa/subcommand.py
- src/cappa/type_view.py
- src/cappa/typing.py
- tests/arg/test_invalid_annotation_combination.py
- tests/invoke/test_invalid_depdendency.py
- tests/test_manually_built.py
- uv.lock
~Not going to work in the short term. Some of the required functionality isn't merged yet, and none of it is in a released version.~
~Also, type-lens only supports python 3.9+, which is unfortunate. Although https://pypistats.org/packages/cappa maybe implies 3.8 is currently only installed when CI runs.~
~Also, all the variable names are currently "annotation", but probably ought to be `type_view`, so `annotation.annotation` doesn't look so stupid~
Externalize all the various little version-specific python typing handling and various typing related utilities into the `type-lens` package. Much of the type-lens API we use came from cappa's impls, but rebased on the much more comprehensive `TypeView` base provided by it.
> refactor: Adopt the type-lens package.

- docs/source/arg.md
- src/cappa/arg.py
- src/cappa/command.py
- src/cappa/destructure.py
- src/cappa/help.py
- src/cappa/parser.py
- tests/arg/test_destructured.py
An idea that came out of https://github.com/DanCardin/cappa/discussions/137. Basically, by fanning out CLI parameters on a nested object into the containing command structure.
> feat: Introduce `Arg.destructure()` and `Arg.has_value`.

- .readthedocs.yml
- CHANGELOG.md
- docs/pyproject.toml
- docs/source/api.md
- docs/source/arg.md
- docs/source/backends.md
- docs/source/conf.py
- docs/uv.lock
- pyproject.toml
- src/cappa/__init__.py
- src/cappa/arg.py
- src/cappa/command.py
- src/cappa/destructure.py
- src/cappa/invoke.py
- src/cappa/output.py
- src/cappa/parse.py
- tests/arg/test_parse.py
- tests/arg/test_parse_dataclass_like.py
- tests/test_manually_built.py
- uv.lock
~This is probably blocked on https://github.com/DanCardin/cappa/pull/117. Realistically, the current `annotation` and `extra_annotations` used by the parsers is bad DX in comparison to something like `TypeView`. If all the parsers are going to end up refactored to be defined in terms of single-level value/annotation, it's going to make a lot more sense when the actual annotation bit is a TypeView instead.~
Result based of discussion from https://github.com/DanCardin/cappa/discussions/137
The main problem with automatic dataclass-like inference, is that we can't know, without the annotation and an explicit decision from the user, whether a `list[T]` input is the appropriate input for the class itself, or if it wants the inputs to be splatted into the constructor.
For anything where the …
>  feat: Support native inference parser for dataclass-like annotations. 

- CHANGELOG.md
- pyproject.toml
- src/cappa/command.py
- tests/arg/test_show_default.py
- tests/help/test_help_formatter.py
- tests/utils.py
Fixes https://github.com/DanCardin/cappa/issues/173
> fix: invoke(help_formatter=...) not applying to explicitly decorated commands.

- CHANGELOG.md
- pyproject.toml
- src/cappa/class_inspect.py
- src/cappa/command.py
- src/cappa/invoke.py
- tests/arg/test_parse_method.py
- uv.lock
Fixes https://github.com/DanCardin/cappa/issues/176
> fix: Incorrect handling of methods in Arg.parse.

- CHANGELOG.md
- pyproject.toml
- src/cappa/arg.py
- src/cappa/argparse.py
- src/cappa/parse.py
- src/cappa/parser.py
- tests/arg/test_choices.py
- tests/arg/test_literal.py
- tests/arg/test_literal_intermixed_union.py
- tests/arg/test_literal_mulitple_variant.py
- tests/arg/test_literal_sequence.py
- uv.lock
Fixes https://github.com/DanCardin/cappa/issues/170.
~Although i still want to look at this a little bit more. this does add some weird code duplication/different branches. Although I suppose some of that already existed before, it was just built into the parser.~
In order to avoid needing to physically manipulate the annotations, this PR drops the nicer "choices" `invalid choice: 'thename' (choose from 'one', 'two', 'three', 4)`-style error messages for annotations like `Union[Literal['one'], Literal['two']]`, because it becomes impractical to support.
Instead such annotations get the union-like error message
```
invalid value for 'name': possible variants
- literal['one']: invalid choice: 'foo'
- literal['two']: invalid choice: 'foo'
```
which is still clear, but not as nice and …
> fix: Perform choices validation after parse/mapping time.

- src/cappa/class_inspect.py
- tests/test_base.py
> fix: Skip non-init fields in dataclasses.

- CHANGELOG.md
- docs/source/arg.md
- src/cappa/arg.py
- src/cappa/default.py
- src/cappa/help.py
- tests/arg/test_show_default.py
Fixes https://github.com/DanCardin/cappa/issues/184
> feat: Add DefaultFormatter as optional input to `show_default`.

- CHANGELOG.md
- pyproject.toml
- src/cappa/default.py
- tests/arg/test_show_default.py
Fixes https://github.com/DanCardin/cappa/issues/190
> fix: Default formatting when value is None/Empty and formatter is supplied.

- CHANGELOG.md
- docs/source/arg.md
- pyproject.toml
- src/cappa/__init__.py
- uv.lock
Addresses an issue in https://github.com/DanCardin/cappa/discussions/195
> fix: Reexport Empty/EmptyType types at the root.

- CHANGELOG.md
- pyproject.toml
- src/cappa/parser.py
- tests/arg/test_propagate.py
- uv.lock
Fixes https://github.com/DanCardin/cappa/issues/197
> fix: Ensure  args supply the correct parent context to the arg's action handler.

- .github/workflows/test.yml
- CHANGELOG.md
- pyproject.toml
- src/cappa/default.py
- tests/arg/test_default_env_missing.py
- uv.lock
Fixes https://github.com/DanCardin/cappa/issues/199
> fix: Coerce `Env(default=None)` to `Empty` to avoid interpreting the value as a string.

- CHANGELOG.md
- pyproject.toml
- src/cappa/parser.py
- tests/parser/test_explicit_equal_option.py
Currently, when an explicit arg contains `=` in the value (e.g. `--my-filter-arg='foo == bar'`) cappa will crash when attempting to parse the explicit arg as `arg.split('=')` returns more than the two expected values. This PR is a fix for that bug.
> fix: Handle multiple = in explicit arg

- pyproject.toml
Hi,
First of all, thanks a lot for writing and maintaining cappa!
What do you think about this trivial change that bumps the dependency versions of `typing-extensions` and `rich` so that `import cappa` would work at all? :)
G'luck,
Peter
> Require rich 10.2.0 and typing-extensions 4.12.0

- CHANGELOG.md
- src/cappa/completion/base.py
- src/cappa/completion/types.py
- src/cappa/help.py
- src/cappa/parser.py
- tests/completion/test_option.py
- tests/completion/test_subcommand.py
fixes https://github.com/DanCardin/cappa/issues/219
* Includes the `<value_name>` of completions that dont have an explicit help to disambiguate them.
* Performs help formatting (to include choices/default) for completion. This was previously just the raw help text.
Notice, it includes it for options that only have a default component (because it's not explicit help text) because it can end up trivially duplicated.
> fix: visual grouping of undocumented zsh completions.
