- src/cappa/base.py
Just started using Cappa, I love it. Thanks!
> Fix docstring indentation in base

- poetry.lock
- pyproject.toml
Fixes https://github.com/DanCardin/cappa/issues/23
> fix: Loosen version specifiers.

- pyproject.toml
Not sure if you intentionally left it empty. Feel free to close in that case!
> Add description to project metadata

- CHANGELOG.md
- pyproject.toml
- src/cappa/arg.py
- src/cappa/argparse.py
- src/cappa/parser.py
- tests/parser/test_concatenated_short_options.py
Fixes https://github.com/DanCardin/cappa/issues/28
> fix: Improve behavior consuming concatenated short arguments

- CHANGELOG.md
- pyproject.toml
- src/cappa/invoke.py
- tests/invoke/test_only_requires_leaf_invoke_fn.py
Fixes https://github.com/DanCardin/cappa/issues/42
> fix: Invoke the specific callable subcommand instance being targeted.

- CHANGELOG.md
- docs/source/arg.md
- pyproject.toml
- src/cappa/arg.py
- src/cappa/argparse.py
- src/cappa/parser.py
- tests/arg/test_required.py
- tests/parser/test_num_args.py
Fixes https://github.com/DanCardin/cappa/issues/40
Fixes https://github.com/DanCardin/cappa/issues/44
> fix: Apply num_args=0 when custom actions.

- CHANGELOG.md
- pyproject.toml
- src/cappa/arg.py
- src/cappa/command.py
- src/cappa/help.py
- src/cappa/parser.py
- tests/arg/test_required.py
- tests/arg/test_value_name.py
Fixes https://github.com/DanCardin/cappa/issues/55
> fix: Disallow required=False and lack of default.

- CHANGELOG.md
- pyproject.toml
- src/cappa/output.py
- tests/help/test_line_wrapping.py
Fixes https://github.com/DanCardin/cappa/issues/59
> fix: Ignored line-wrapping text.

- CHANGELOG.md
- Makefile
- docs/source/help.md
- poetry.lock
- pyproject.toml
- src/cappa/command.py
- src/cappa/parser.py
- tests/help/test_consistent_among_subcommands.py
- tests/parser/test_option_after_bad_arg.py
Fixes https://github.com/DanCardin/cappa/issues/62
> feat: Make docstring-parser dependency optional.

- src/cappa/command.py
- src/cappa/testing.py
- tests/help/test_docstring.py
- tests/help/test_name.py
- tests/test_docstring.py
- tests/utils.py
Fixes #64.
Needs tests :slightly_smiling_face: 
Feel free to push to this branch! `gh pr checkout 65`
> fix: Keep using commands' class docstring as help/description

- CHANGELOG.md
- pyproject.toml
- src/cappa/output.py
- tests/help/test_docstring.py
> fix: Escape rendered displayable

- pyproject.toml
- src/cappa/base.py
Fix: https://github.com/DanCardin/cappa/issues/68
> fix: Erroneous return type annotation for invoke.

- CHANGELOG.md
- docs/source/api.md
- docs/source/asyncio.md
- docs/source/index.md
- pyproject.toml
- src/cappa/__init__.py
- src/cappa/base.py
- src/cappa/invoke.py
- src/cappa/testing.py
- tests/invoke/test_async_function.py
- tests/utils.py
Fixes https://github.com/DanCardin/cappa/issues/76
> feat: Add ability to resolve async dependencies through new `invoke_async`.

- docs/source/examples.md
small typo fixed :)
great great library !
> docs: fix typo

- CHANGELOG.md
- docs/source/annotation.md
- pyproject.toml
- src/cappa/annotation.py
- tests/arg/test_date.py
Fixes https://github.com/DanCardin/cappa/issues/123
>  feat: Update automatic inference to support (isoformat) date, time, and datetime parsing.

- CHANGELOG.md
- pyproject.toml
- src/cappa/help.py
- tests/help/test_markdown.py
- tests/help/test_name.py
Fixes https://github.com/DanCardin/cappa/issues/131
> fix: Route arg help formatting through markdown processing.

- README.md
- docs/source/api.md
- docs/source/arg.md
- docs/source/functions_and_methods.md
- docs/source/index.md
- src/cappa/arg.py
Fixes https://github.com/DanCardin/cappa/issues/166
> docs: Ensure documentation of Group object.

- src/cappa/arg.py
- src/cappa/argparse.py
- src/cappa/ext/docutils.py
- src/cappa/help.py
- src/cappa/subcommand.py
- tests/arg/test_exclusive_group.py
- tests/help/test_group.py
- tests/subcommand/test_group.py
Fixes https://github.com/DanCardin/cappa/issues/167
Fixes https://github.com/DanCardin/cappa/issues/163
> feat: Add Group.section to enable ordering of groups separately from the items within them.

- CHANGELOG.md
- docs/source/arg.md
- pyproject.toml
- src/cappa/arg.py
- src/cappa/argparse.py
- src/cappa/command.py
- src/cappa/destructure.py
- src/cappa/help.py
- src/cappa/parser.py
- src/cappa/subcommand.py
- tests/arg/test_propagate.py
Also significantly refactors the native parser backend internals to ease the implementation of the feature.
> feat: Implement propagated arguments.

- CHANGELOG.md
- pyproject.toml
- src/cappa/argparse.py
- src/cappa/parser.py
- tests/arg/test_default_value_from.py
- uv.lock
Fixes https://github.com/DanCardin/cappa/issues/193
> fix: Optional positional arguments should not get a default value from their action.

- Makefile
- README.md
- docs/source/_static/example.svg
Fixes https://github.com/DanCardin/cappa/issues/207
> docs: Improve readme example.

- src/cappa/help.py
- src/cappa/output.py
- tests/help/test_help_formatter.py
- tests/help/test_text_format.py
- uv.lock
> Add ability to style individual argument help components

- CHANGELOG.md
- docs/source/arg.md
- pyproject.toml
- src/cappa/parse.py
- tests/arg/test_choices.py
- uv.lock
Fixes https://github.com/DanCardin/cappa/issues/226
> fix: Explicit choice sequence runtime error.

- CHANGELOG.md
- pyproject.toml
- src/cappa/arg.py
- src/cappa/command.py
- src/cappa/destructure.py
- tests/arg/test_destructured.py
- tests/arg/test_destructured_collision.py
- tests/arg/test_destructured_count.py
- tests/arg/test_destructured_explicit.py
- tests/arg/test_destructured_optional.py
- tests/arg/test_destructured_subcommand.py
- uv.lock
Fixes https://github.com/DanCardin/cappa/issues/232
> fix: Destructured relative context, e.g. counting.

- CHANGELOG.md
- pyproject.toml
- src/cappa/arg.py
- src/cappa/destructure.py
- tests/arg/test_destructured.py
- tests/arg/test_destructured_implicit_default.py
- tests/arg/test_destructured_optional.py
- tests/arg/test_destructured_union.py
Fixes https://github.com/DanCardin/cappa/pull/237
> fix: Infer class constructor as default for `Destructured` class.
